import {
  faCoffee,
  faUser,
  faEnvelope,
  faHome,
  faUserPlus,
  faQuestionCircle,
  faSlidersH,
  faCreditCard,
  faTruck,
  faSearch,
  faCheckCircle,
  faComments,
  faFlagCheckered,
  faShieldAlt,
  faBell,
  faExclamationCircle,
  faBars,
} from "@fortawesome/free-solid-svg-icons";

export const faIcons = [
  faCoffee,
  faUser,
  faEnvelope,
  faHome,
  faUserPlus,
  faQuestionCircle,
  faSlidersH,
  faCreditCard,
  faTruck,
  faSearch,
  faCheckCircle,
  faComments,
  faFlagCheckered,
  faShieldAlt,
  faBell,
  faExclamationCircle,
  faBars,
];
